# Generated by Django 2.2.8 on 2020-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200425_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='uploads/article/2020/04/25/t02.jpg', upload_to='uploads/article/%Y/%m/%d', verbose_name='文章图片'),
        ),
    ]
