# Generated by Django 2.2.8 on 2020-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='icon',
            field=models.CharField(default='images/tx1.jpg', max_length=50, verbose_name='头像'),
        ),
    ]
